### ISSUE TITLE
USER STORY: View Navigation Bar

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#1]
As a **User** I can **view the navigation bar throughout the site** so that **I can easily navigate between pages from anywhere**

**Acceptance Criteria**

AC 1: Navigation bar component is visible at the top of every page
AC 2: Navbar contains the following: logo and links to:

**Sign In User**
1. Home
2. Create
3. Meetup
4. User Action
- Profile
- Sign out

**Sign Out User**
1. Home
2. Meetup
3. Sign In
4. Sign out

----

**Tasks:**
- [x] Design navbar component
- [x] Create JSX
- [x] Create CSS module
- [x] Wire up pages
