### ISSUE TITLE
USER STORY: Edit Comment

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#12]
As a **logged In user** I can **edit my own comments** so that **I can update or change the content of my existing comments.**

**Acceptance Criteria**
 AC 1: Logged In users are able to edit their own comments
 AC 2: A dropdown menu will be available to the user on their own comments in the comment list
 AC 3: The user can click 'edit' in the dropdown menu and update the comment

------

**Tasks**
- [x] Add edit button to comment dropdown menu
- [x] Create Edit Form
- [x] Create CSS
- [x]  API request- put request to the API
