### ISSUE TITLE
USER STORY: Delete comment

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#13]
As a **logged in user** I can **delete a comment that I created** so that **I can remove comments as I see fit**

**Acceptance Criteria**
AC 1: Once logged in, user can see the delete button next to all the comments that they created
AC 2:  comment is removed from the comment list and deleted from the database

---

**Tasks:**
- [x]  Design - delete icon
- [x]  Create HTML, CSS, JSX
- [x]  Create API requests - destroy request to API
