### ISSUE TITLE
USER STORY: Profile page

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#14]
As a **User** I can **view the profile page of another user** so that **I can see more details about that user**

**Acceptance Criteria**
AC 1: Profile page includes all additional profile model fields - bio, name, email, website, social medial links,
AC 2: Profile page also includes followers count, followed count, post count and events posted count..
AC 3: Profile can be viewed by all users

----

**Tasks:**
- [x]  Design profile page
- [x]  Create profile component
- [x]  Create CSS, JSX -
- [x]  Create API requests - pull through all profile model fields
