### ISSUE TITLE
USER STORY: Edit Profile

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#15]
As a **User** I can **edit my own profile details** so that **I can keep my profile information update**

**Acceptance Criteria**
AC 1: Add EditDelete Component dropdown to the profile page
AC 2: Only show the edit dropdown when the user is logged in, and if the logged in username matches the profile username.
AC 3: User can edit all fields of the profile

-----

**Tasks:**
- [ ]  Design - Profile page edit form
- [ ]  Create -  CSS, JSX - Link to edit component
- [ ]  Create-  API requests - call put request to update existing profile instance
- [ ] Wire up
