### ISSUE TITLE
USER STORY: Follow/Unfollow

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#16]
As a **logged in user** I can **follow and unfollow other users** so that **I can easily add or remove users from my follower list** 

AC 1: Once logged in, User can see a follow/unfollow buttons next to each profile
AC 2: Follow/Unfollow buttons visible on Discover Profile  list and on the home page and post page

---

**Tasks:**
- [x]  Design follow/unfollow buttons
- [x]  Create CSS, JSX - toggle button between follow/unfollow on click
- [x]  Create API requests - Create follow request to API
