### ISSUE TITLE
USER STORY: Create Event

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#18]
As a **logged in user** I can **create an event** so that **I can promote an event in Pythonista app**

**Acceptance Criteria**
AC 1: Add Event button visible on the Events page underneath nav bar when a user is logged in .
AC 2: Create event form lets user upload image, and add details of event - title, date, description.
AC 3: Event title, event_date, event start and end time are required fields.
AC 4: Add event_date validation , that user can not create event with invalid event_date

-----

**Tasks:**
- [x]  Design Create Event Form
- [x]  Create  CSS, JSX - Design form page layout. Get upload photo image
- [x]  Create API requests - set up Post to new event to API
