### ISSUE TITLE
USER STORY: Edit an Event

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#19]
As a **logged in user** I can **edit my own events** so that **I can change the details or correct mistakes**

**Acceptance Criteria:**
AC 1: If event profile id matches the logged in user profile id, show edit button next to event on event detail page
AC 2: Edit form allows user to change the image, title, description and event date. and time, organizers or location.
AC 3: Only logged In user can edit event post

-----

**Tasks:**
- [x]  Create - Edit event page, = pre-populated create event page
- [x]  Create CSS, JSX - design the same as the create event page
- [x]  Create API requests - put request to update existing event
