### ISSUE TITLE
USER STORY: Authentication - Sign up

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#2]
As a **User** I can **Sign into the app** so that **I can access full site functionality**

**Acceptance Criteria**

AC1: Login link accessible in the navbar to logged out users
AC2: Login link takes user to enter credentials and login to site
AC3: After login, user redirected to homepage
AC4:  Maintain user logged-in status until, she/he choose to log out

----

**Tasks:**

- [x]  Create Sign up component
- [x]  Create CSS module
- [x]  Create Sign Up Form
- [x]  Create API requests - send request to API `dj-auth` to check credentials
- [x]  Add  Refreshing access tokens
