### ISSUE TITLE
USER STORY: Delete an Event

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#20]
As a **logged in user** I can **delete my own events** so that **I can remove events from event list on my profile**

**Acceptance Criteria:**
AC 1: If event profile id matches the logged in user profile id, show delete button next to event on event detail page
AC 2: Removes event from all lists and from the database

------

**Tasks:**
- [x] Design - Confirm deletion modal popup
- [x]  Create CSS, JSX -
- [x]  Create API requests - destroy request to update existing event
