### ISSUE TITLE
USER STORY: View Event page

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#21]
As a **User** I can **see the details of a single event** so that **I can read everything relating that events**

**Acceptance Criteria**
AC 1: Event page displays single event id details
AC 2: User, regardless of login status can view the event
AC 3: Event shows: image, title, description, created_at date, event_date, join_count, , conversation_count, location, organizer of the event, profile pic, username of user who posted it.

---

**Tasks:**
- [x]  Create Event Page component
- [x]  Create HTML, CSS, JSX - style
- [x]  Create API requests - request single event ID
