### ISSUE TITLE
USER STORY: Search Event

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#22]
As a **user** I can **search the events list** so that **I can find events that interest me more**

**Acceptance Criteria**
AC 1: Search bar above the events list on events page
AC 2: Search results shown based on title, username or event_date

-----

**Tasks**
- [x]  Design search bar component
- [x]  Create CSS, JSX - style search bar
- [x]  Create API requests - request filtered results based on search input
