### ISSUE TITLE
USER STORY: Mark Join on an Event

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#23]
As a **logged in user** I can **mark Join to an event post** so that **I can publicly display my interest in an event**

**Acceptance Criteria**
AC 1: Join button under all event posts
AC 2: Join button active only when user logged in
AC 3: If user not logged in, message on hover tells them they must be logged in to mark Join in an event
AC 4: Marking Join increases total interested count for that event

------

**Tasks:**
- [x]  Design - Join button and icon
- [x]  Create CSS, JSX - set up authentication against logged out users
- [x]  Create API requests - Post interested instance to interested table
