### ISSUE TITLE
USER STORY: Delete Conversation

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#26]
As a **logged in user** I can **delete a conversation that I created** so that **I can remove my conversation from the list.**

**Acceptance Criteria**
AC 1: Once logged in, user can see the delete button next to all the conversation that they created
AC 2: Conversation is removed from the conversation list and deleted from the database

**Tasks:**
- [x]  Design - delete icon
- [x]  Create HTML, CSS, JSX
- [x]  Create API requests - destroy request to API
