### ISSUE TITLE
USER STORY: Authentication - Sign in

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#3]
As a **User** I can **Sign Out out of the app** so that **I can stop accessing full site functionality**  while not actively contributing to the site.

**Acceptance Criteria**
AC1: Sign out Icon accessible in the navbar to logged in/ logged out users
AC 2:  After logout, user redirected to homepage

------

**Tasks:**

- [x] Create Sign In component
- [x]  Create CSS module
- [x]  Create Sign In Form
- [x]  Create API requests - send request to API` dj-auth` to check credentials
