### ISSUE TITLE
USER STORY: Profile Picture

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#4]
As a **User** I can **view user's profile picture** so that **I can easily identify users of the application**

**Acceptance Criteria**
AC1: Default avatar assigned to all users on signup
AC2:  Users can upload custom avatar image in profile page.
AC3: Avatar shown next to profile in the Discover People list in Home page
AC4: Avatar displayed next to all personally created items in the site 
- Profile
- Posts
- Meetup Posts
- Comments

------

**Tasks:**
- [x]  Design default avatar 
- [x]  Create Avatar component
- [x]  Create CSS
- [x]  Create API requests
