### ISSUE TITLE
USER STORY:  Create posts

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#5]
As a **User** I can **create posts** so that **I can share my journey as Python Developer  with the world!**

**Acceptance Criteria**
AC1: Add a visible Create Post icon on Navbar in case of user logged In 
AC2: Create a Post Form that let users can write post content and upload image 

-----

**Tasks:**
- [x] Create Post Form
- [x] Create CSS Module
- [x]  Create API requests
- [x] Wire up the Create Post page
