### ISSUE TITLE
USER STORY: View a Post

### ISSUE THREAD

**Issue by sediqa01** [sediqa01/pythonista#6]
As a **User** I can **view the details of a single post** so that **I can learn more about it**

**Acceptance Criteria**
AC 1: Post page displays single post details
AC2: Post shows the Post Content, Post Image, Post Date, Likes , Comments and the user name and profile picture of whom posted.
AC3: Post page filter each post by its ID

----

**Tasks:**
- [x]  Create Post component
- [x]  Create CSS module
- [x]  Create API requests - request single post ID
